CC = gcc
CFLAGS = -Wall -Wextra -Werror -std=c99
LDFLAGS =
LEX = flex
YACC = bison

.PHONY: all clean

all: feedscript

feedscript: main.o lexer.o parser.o evaluator.o
	$(CC) $(LDFLAGS) -o $@ $^

main.o: main.c parser.h evaluator.h
	$(CC) $(CFLAGS) -c -o $@ $<

lexer.o: lexer.c parser.h
	$(CC) $(CFLAGS) -c -o $@ $<

parser.o: parser.c parser.h
	$(CC) $(CFLAGS) -c -o $@ $<

evaluator.o: evaluator.c evaluator.h parser.h
	$(CC) $(CFLAGS) -c -o $@ $<

lexer.c: lexer.l
	$(LEX) -o $@ $<

parser.c parser.h: parser.y
	$(YACC) -d -o parser.c $<

clean:
	rm -f feedscript *.o lexer.c parser.c parser.h
